#!/usr/bin/env bash

ICON=""

read -r cpu_user cpu_nice cpu_system cpu_idle _ < <(grep '^cpu ' /proc/stat | awk '{print $2, $3, $4, $5}')
sleep 0.5
read -r cpu_user2 cpu_nice2 cpu_system2 cpu_idle2 _ < <(grep '^cpu ' /proc/stat | awk '{print $2, $3, $4, $5}')

idle=$((cpu_idle2 - cpu_idle))
used=$(((cpu_user2 - cpu_user) + (cpu_nice2 - cpu_nice) + (cpu_system2 - cpu_system)))

total=$((used + idle))
if [ "$total" -gt 0 ]; then
  usage=$((100 * used / total))
else
  usage=0
fi

# Ícone amarelo, texto padrão
echo "<span foreground='#e5c07b'>$ICON</span> ${usage}%"
