#!/usr/bin/env bash

ICON=""

if [ "$BLOCK_BUTTON" = "1" ]; then
  i3-nagbar -t warning -m 'Desligar o sistema?' -B 'Desligar' 'systemctl poweroff'
fi

# Ícone vermelho
echo "<span foreground='#ff5555'>$ICON</span>"
